presubmits:
  cert-manager/istio-csr:

  - name: pull-cert-manager-istio-csr-verify
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-istio-csr-unit
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-unit
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-istio-csr-test-ecc
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-ecc
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-istio-csr-ca-rotation
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-carotation
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"
  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.14
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-14
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.14.6"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.15
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-15
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.15.5"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.16
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-16
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.16.7"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.17
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-17
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.17.8"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.18
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-18
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.18.7"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.26, istio v1.17
  - name: pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-19
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.26.1"
        - name: ISTIO_VERSION
          value: "1.19.6"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.29, istio v1.20
  - name: pull-cert-manager-istio-csr-k8s-v1-29-istio-v1-20
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-e2e
        resources:
          requests:
            cpu: 3500m
            memory: 6Gi
        env:
        - name: K8S_VERSION
          value: "1.29.1"
        - name: ISTIO_VERSION
          value: "1.20.2"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
          - name: ndots
            value: "1"
