presubmits:
  cert-manager/helm-tool:

  - name: pull-cert-manager-helm-tool-verify
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-helm-tool-test
    decorate: true
    always_run: true
    labels:
      preset-go-cache: "true"
      preset-local-cache: "true"
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/cert-manager-tests-trusted/cert-manager-infra-images/make-dind:20240418-15f03a5-bookworm
        args:
        - runner
        - make
        - vendor-go
        - test-unit
        resources:
          requests:
            cpu: 1
            memory: 1Gi
